version: 2.1

jobs:
  mvn:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package -Dmaven.test.skip=true
  docker_build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: docker login --username=liyifeng@xlauncher registry.cn-hangzhou.aliyuncs.com -p=Liyifeng0 
      - run: docker build -f Dockerfile -t registry.cn-hangzhou.aliyuncs.com/launcher/lyf-demo:v1 
      - run: docker push registry.cn-hangzhou.aliyuncs.com/launcher/lyf-demo:v1

workflows:
  workflow1:
    jobs:
      - mvn
      - docker_build
